use scoped AdminRegionLevel enum
to fix build with Qt 5.6 and GCC 13.4.

AdminRegionLevel contains value "State" that conflicts with
enum name "State" in QFutureInterfaceBase (Qt 5.6), when library
is compiled with C++20 standard, GCC 13.4.

 /usr/include/qt5/QtCore/qfutureinterface.h:282:33: error: expected ')' before 'initialState'
   282 |     QFutureInterface<void>(State initialState = NoState)
       |                           ~     ^~~~~~~~~~~~~
       |                                 )